### ISSUE TITLE
Comments don't appear to load when uBlock Origin is enabled

### ISSUE THREAD

**Issue by Sirosky** [sheodox/alexandrite#3]
As the title indicates, comments don't load when uBlock Origin is enabled.

![image](https://github.com/sheodox/alexandrite/assets/2752448/0f1ea7c6-7775-43ec-9e6f-6663c4ec33e2)

The filters I'm using. I don't have any custom filters for Alexandrite.

![image](https://github.com/sheodox/alexandrite/assets/2752448/90ff3325-0a36-46e0-8ef9-4e6a996773a6)

EDIT: Actually, oddly enough, even with uBlock Origin off, on the Top feed, comments don't work either (while they work in the Hot feed).

**Comment by DDYBDAHL** [comment]
Seems to be working for me. I have just the default uBlock Origin setup though. 

![image](https://github.com/sheodox/alexandrite/assets/86426012/f6dc25a1-69a1-4268-a5ca-1183b5403ec8)


![image](https://github.com/sheodox/alexandrite/assets/86426012/a60a9aef-b65d-4f07-af0e-17a3123a5822)

**Comment by sheodox** [comment]
Hey, thanks for the issue.

This one's kinda funny, over the last two weeks while working on this I assumed there were federation issues between a couple instances I use, because I'd consistently not see comments load when viewing comments on threads from the other instance. So when I saw this issue I went to find a post like that to prove that's what it was, but then my instance showed the comments, and I realized I was wrong this whole time.

The actual problem isn't related to uBlock Origin at all, it's that when loading various feeds (posts/comments) you're able to specify a "type" (like Subscribed, Local, or All, like you see at the top of various feeds). The problem is that I wasn't specifying the type "All" when asking Lemmy for comments for a post, so it'd use some default probably which doesn't seem to be "All". Because there's nothing on the official Lemmy UI for changing that type when viewing comments under a post I didn't even think of it.

It's a super easy fix, I'll do that quick.
