### ISSUE TITLE
[Feature Request] Favorite communities

### ISSUE THREAD

**Issue by SpringMango** [sheodox/alexandrite#33]
Being able to favorite certain communities for easy access or even creating groups similar to what Apollo had would be fantastic.

**Comment by SpringMango** [comment]
Just found out you can indeed favorite communities! So cool. 

It would still be really awesome to group communities. Such as creating a "Gaming" group which consists of several gaming related communities. 

Keep up the awesome work, Alexandrite is an amazing UI!

**Comment by sheodox** [comment]
That favorite button is definitely too hidden. You're definitely not the first who had no idea it was there, going to make some changes to make it more discoverable! With the next release now that button will show up whenever you hover over anywhere over the row, not just the icon.

![image](https://github.com/sheodox/alexandrite/assets/3468630/3a6112b5-b418-42f8-959c-026f89ea30c7)

Grouping is a neat idea. I have a feeling the next request as soon as I add that is a "multi-reddit"-like feature which in order to do properly needs to be supported by Lemmy. Found an issue over there for that: https://github.com/LemmyNet/lemmy/issues/818
