### ISSUE TITLE
(BUG) Cannot login to lemmy.sdf.org

### ISSUE THREAD

**Issue by dtantono** [sheodox/alexandrite#85]
Hello
I can login to the instance directly. But, on Alexandrite I cannot login to lemmy.sdf.org and it says instance expired message. What is that mean?

![image](https://github.com/sheodox/alexandrite/assets/29157187/008036f5-57e7-49df-a009-464a93196563)

**Comment by sheodox** [comment]
Hello!

That's because that instance is running an RC of version of Lemmy 0.19, I haven't gotten around to finishing my 0.19 work, but I will try to get that done today! The way authentication is handled is different, so things need to be updated to handle the new methods, so currently on 0.19 instances it'll always think your login session expired until I get that fixed!

**Comment by janvkn** [comment]
Any update on this? 

0.19 has been released officially, and instances are starting to migrate to it, so soon people won't be able to login anymore with Alexandrite.

**Comment by sheodox** [comment]
Hey, the plan was to do it today. Having some friends come over for a craft day and a couple of us are gonna code, and I'm already halfway done so shouldn't take too long!
